name: Semantic-Release Artefact Installer
description: GitHub Action installing NPM Artefacts for Semantic-Release with NPM-Cache

inputs:
  NODE_VERSION:
    required: false
    default: "20"
    type: string

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cp ${{ github.action_path }}/package.json .
        cp ${{ github.action_path }}/package-lock.json .
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    - name: Install Semantic-Release Dependencies
      shell: bash
      run: |
        npm ci
    - name: Copy Semantic-Release Custom Scripts
      shell: bash
      run: |
        cp ${{ github.action_path }}/verifyRelease.sh ./.github
