name: Semantic-Release Artefact Installer
description: GitHub Action installing NPM Artefacts for Semantic-Release with NPM-Cache

inputs:
  NODE_VERSION:
    required: false
    default: "20"
    type: string

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cp ${{ github.action_path }}/package.json .
        cp ${{ github.action_path }}/package-lock.json .
    - id: semantic-release-cache
      uses: actions/cache@v3
      with:
        path: 'node_modules'
        key: ${{ runner.os }}-semantic-release-${{ hashFiles('package-lock.json') }}
    - name: Install Semantic-Release Dependencies
      if: steps.semantic-release-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        npm ci
    - name: Copy Semantic-Release Custom Scripts
      shell: bash
      run: |
        cp ${{ github.action_path }}/verifyRelease.sh ./.github
